### ISSUE TITLE
Jerry: be consistent with the error handling for server responses

### ISSUE THREAD

**Issue by juliebarwick** [7satsumas/fec-project#55]
https://github.com/7satsumas/fec-project/blob/9a71e5661791a6b05e6d5ef6e2650275d1162deb/server/controllers/questionsController.js#L47

Make sure to send a response (status codes in 400s or 500s) to the client if there's an error besides just console.logging the error. Double check all route `.catch` to be consistent.

**Comment by jerry-jma** [comment]
Thank you for pointing it out. Resolved.
